=== modnaut/primary/web/WEB-INF/xsd/DatabaseProperties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="databaseMetaData">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="database" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="database">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="driverclassname" type="property" minOccurs="0" maxOccurs="1"/>
				<xs:element name="url" type="property" minOccurs="0" maxOccurs="1"/>
				<xs:element name="username" type="property" minOccurs="0" maxOccurs="1"/>
				<xs:element name="password" type="property" minOccurs="0" maxOccurs="1"/>
				<xs:element name="maxactive" type="property" minOccurs="0" maxOccurs="1"/>
				<xs:element name="maxidle" type="property" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" type="databaseType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="property">
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:simpleType name="databaseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MYSQL"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== modnaut/primary/web/WEB-INF/xml/DatabaseProperties.xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseMetaData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/DatabaseProperties.xsd">
	<database name="development" type="MYSQL">
		<driverclassname value="com.mysql.jdbc.Driver"/>
		<url value="jdbc:mysql://localhost:3306/common"/>
		<username value="modnaut00"/>
		<password value="zp4X263tTSv06On"/>
		<maxactive value="15"/>
		<maxidle value="3"/>
	</database>	
</databaseMetaData>
