=== modnaut/primary/web/WEB-INF/xsd/SqlMetaData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="sqlMetaData">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="query" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="connection" type="connectionType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="query">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="statement" type="statementType" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="parameters" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="action" type="actionType" use="required"/>
			<xs:attribute name="type" type="queryType" use="required"/>
			<xs:attribute name="connection" type="connectionType" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="optional"/>
			<xs:attribute name="type" type="parameterType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="statementType">
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:simpleType name="queryType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SP"/>
			<xs:enumeration value="QUERY"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="actionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SELECT"/>
			<xs:enumeration value="ACTION"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="parameterType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TINYINT"/>
			<xs:enumeration value="SMALLINT"/>
			<xs:enumeration value="MEDIUMINT"/>
			<xs:enumeration value="INT"/>
			<xs:enumeration value="BIGINT"/>
			<xs:enumeration value="BIT"/>
			<xs:enumeration value="FLOAT"/>
			<xs:enumeration value="DOUBLE"/>
			<xs:enumeration value="DECIMAL"/>
			<xs:enumeration value="CHAR"/>
			<xs:enumeration value="VARCHAR"/>
			<xs:enumeration value="TINYTEXT"/>
			<xs:enumeration value="TEXT"/>
			<xs:enumeration value="MEDIUMTEXT"/>
			<xs:enumeration value="LONGTEXT"/>
			<xs:enumeration value="BINARY"/>
			<xs:enumeration value="VARBINARY"/>
			<xs:enumeration value="TINYBLOB"/>
			<xs:enumeration value="BLOB"/>
			<xs:enumeration value="MEDIUMBLOB"/>
			<xs:enumeration value="LONGBLOB"/>
			<xs:enumeration value="DATE"/>
			<xs:enumeration value="TIME"/>
			<xs:enumeration value="YEAR"/>
			<xs:enumeration value="DATETIME"/>
			<xs:enumeration value="TIMESTAMP"/>
			<xs:enumeration value="OBJECT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="connectionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MYSQL"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== modnaut/primary/web/WEB-INF/xml/CommonSqlMetaData.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqlMetaData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/SqlMetaData.xsd">
	<query name="GET_USER_LIST" action="SELECT" type="QUERY">
		<statement value="Select UserName, FirstName, LastName, EmailAddress From Users Where UserId = ?"/>
		<parameters>
			<parameter id="1" name="UserId" type="INT"/>
		</parameters>
	</query>
	<query name="GET_ALL_USERS_ALPHABETICALLY" action="SELECT" type="SP">
		<statement value="Common.GetAllUsersAlphabetically()"/>
	</query>
	<query name="INSERT_USER" action="ACTION" type="QUERY">
		<statement value="INSERT INTO users (UserName, FirstName, LastName, EmailAddress) 
						  VALUES (?, ?, ?, ?)"/>
		<parameters>
			<parameter id="1" name="UserName" type="VARCHAR"/>
			<parameter id="2" name="FirstName" type="VARCHAR"/>
			<parameter id="3" name="LastName" type="VARCHAR"/>
			<parameter id="4" name="EmailAddress" type="VARCHAR"/>
		</parameters>
	</query>
	<query name="AUTHENTICATE_USER" action="SELECT" type="SP">
		<statement value="Common.AuthenticateUser(?, ?)"/>
		<parameters>
			<parameter id="1" name="Email" type="VARCHAR"/>
			<parameter id="2" name="Password" type="VARCHAR"/>
		</parameters>
	</query>
	<query name="INSERT_SESSION" action="ACTION" type="QUERY">
		<statement value="INSERT INTO Common.Session(SessionId, SessionObject, CreatedDate) VALUES (?, ?, CURRENT_TIMESTAMP())"/>
		<parameters>
			<parameter id="1" name="SessionId" type="INT"/>
			<parameter id="2" name="SessionObject" type="BLOB"/>
		</parameters>
	</query>
	<query name="GET_SESSION" action="SELECT" type="QUERY">
		<statement value="SELECT SessionObject, LastModifiedDate FROM Common.Session WHERE SessionId = ?"/>
		<parameters>
			<parameter id="1" name="SessionId" type="INT"/>
		</parameters>
	</query>
	<query name="GET_USER_SESSION" action="SELECT" type="QUERY">
		<statement value="Common.GetUserSession(?)"/>
		<parameters>
			<parameter id="1" name="UserId" type="INT"/>
		</parameters>
	</query>
	<query name="GET_USER" action="SELECT" type="SP">
		<statement value="Common.GetUser(?)"/>
		<parameters>
			<parameter id="1" name="UserId" type="INT"/>
		</parameters>
	</query>
	<query name="GET_USER_TYPES" action="SELECT" type="QUERY">
		<statement value="Select UserTypeCd, Description From Common.UserType Order By Description ASC"/>
	</query>
	<query name="UPDATE_USER" action="ACTION" type="SP">
		<statement value="Common.UpdateUser(?, ?, ?, ?, ?, ?, ?, ?)"/>
		<parameters>
			<parameter id="1" name="UserId" type="INT"/>
			<parameter id="2" name="UserName" type="VARCHAR"/>
			<parameter id="3" name="FirstName" type="VARCHAR"/>
			<parameter id="4" name="LastName" type="VARCHAR"/>
			<parameter id="5" name="EmailAddress" type="VARCHAR"/>
			<parameter id="6" name="HireDateDisabled" type="VARCHAR"/>
			<parameter id="7" name="UserTypeCd" type="VARCHAR"/>
			<parameter id="8" name="UserPassword" type="VARCHAR"/>
		</parameters>
	</query>
</sqlMetaData>
